name: "Test & lint"
on: [push]
jobs:
  test:
    name: greenatom_task tests
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip' # caching pip dependencies
    - run: pip install .[dev]
    - name: Run tests with pytest
      run: |
        pytest .\tests\integration 
        pytest .\tests\unit 

  lint:
    name: greenatom_task lint
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - run: pip install .[dev]
      - name: Run linters
        run: |
          mypy -p src.greenatom_task -v --follow-imports=normal
          ruff check .
